//! The versioned JSONL lifecycle-event schema and its emitter.
//!
//! This module owns processkit-cli's **normative event contract** (`AGENTS.md`,
//! "This repository owns the normative JSONL schema"): every event is one JSON
//! object on its own line, carrying a `schema_version`, written only to the
//! `--jsonl` file — never to stdout, so the child's stream stays pristine
//! (`AGENTS.md`, "Streams are strictly separated"). Adapters (processkit-py's
//! CLI) pin `schema_version` and reimplement these shapes, so the field set here
//! is a public API: `docs/schema.md` is the human-readable normative document and
//! `fixtures/schema/v1/events.jsonl` is the golden material adapters test against
//! (regenerated by [`tests::golden_stream_matches_the_fixture`]).
//!
//! Two field groups are shaped to keep the wire form stable as capabilities grow:
//!
//! - **Enriched member fields (still reserved).** ProcessKit's public API returns
//!   bare PIDs today; the richer per-member snapshot (`ppid` / executable `name` /
//!   `start_time`) is a filed-but-unshipped ProcessKit-rs capability
//!   (`ProcessGroup::members_info()`). So [`Member`] declares those fields as
//!   optional and the emitter fills them from bare PIDs alone, marking every
//!   richer field explicitly **absent** (JSON `null`) rather than inventing a
//!   local process-enumeration path (`AGENTS.md`, "Build strictly on the public
//!   `processkit` API").
//! - **Command line / argv redaction (shipped in T-005).** Command lines carry
//!   secrets, so argv is redacted by default (`AGENTS.md`, "Argv is redacted by
//!   default"): a redacted `command` omits the raw `argv` and instead carries a
//!   one-way SHA-256 fingerprint of argv (`argv_sha256`) plus, for recognized
//!   worker shapes, a categorical `hint` (see [`HINT_RULES`]). Neither can reveal
//!   the command line, so both are filled on **every** run; `--argv-raw` only adds
//!   the raw `argv` array on top. Populating these once-reserved fields does not
//!   change the event's wire shape.

use std::io::Write;
use std::path::Path;
use std::time::{Duration, SystemTime};

use serde::{Deserialize, Serialize};

use processkit::{Command as PkCommand, Mechanism, Outcome, ParentDeathCleanup};

/// The schema version stamped on every event. Part of the compatibility surface:
/// any breaking change to an event's shape is a **major** bump of this number
/// (`docs/schema.md`, "Versioning").
pub const SCHEMA_VERSION: u32 = 1;

/// The wire record actually serialized per line: the common envelope
/// (`schema_version`, `time`) plus the flattened event body (its `event` type tag
/// and payload). Field order here is the on-the-wire order and is stable.
#[derive(Serialize)]
struct Record<'a> {
    schema_version: u32,
    /// Emission time, RFC 3339 UTC with millisecond precision. For `root_exited`
    /// this doubles as the required exit timestamp — the moment the runner
    /// observed the child leave.
    time: String,
    #[serde(flatten)]
    event: &'a Event,
}

/// One lifecycle event. Internally tagged (`"event": "<snake_case>"`) so each line
/// is self-describing; every variant is documented in `docs/schema.md`.
#[derive(Debug, Serialize)]
#[serde(tag = "event", rename_all = "snake_case")]
pub enum Event {
    /// The run has started: the child is spawned into the container and its root
    /// PID, the containment mechanism, the working directory, and the (redacted)
    /// command are known.
    RunStarted {
        run_id: String,
        /// The root child's PID. `null` if the backend did not expose one.
        root_pid: Option<u32>,
        /// `job_object` | `cgroup_v2` | `process_group` (see [`mechanism_str`]).
        mechanism: &'static str,
        /// `whole_tree` | `direct_child_only` | `none`: the cleanup guarantee that
        /// remains if the runner itself dies without running destructors.
        abrupt_cleanup: &'static str,
        /// Working directory the child runs in, or `null` if it could not be
        /// resolved.
        cwd: Option<String>,
        command: CommandInfo,
    },
    /// A point-in-time snapshot of the container's members. PID-only today; the
    /// richer fields are declared but absent (see module docs and [`Member`]).
    MembersSnapshot { members: Vec<Member> },
    /// The root child exited on its own. `code` is set for a normal exit; `signal`
    /// for a Unix signal death; both `null` only for an outcome without either.
    RootExited {
        /// `exited` | `signalled` | `timed_out` | `unknown` (see [`outcome_fields`]).
        outcome: &'static str,
        code: Option<i32>,
        signal: Option<i32>,
    },
    /// Container teardown is beginning; `members_before` is the tree size about to
    /// be reaped.
    CleanupStarted { members_before: usize },
    /// Container teardown finished. `remaining_pids` is a post-hard-kill snapshot
    /// (empty on the Job Object / cgroup mechanisms; on the POSIX process-group
    /// fallback an unreaped just-exited child may still be listed as a member —
    /// see [`ProcessGroup::members`](processkit::ProcessGroup::members)).
    /// `soft_terminate` describes the soft-stop tier for a runner-imposed ending
    /// (`signalled` | `unsupported` | `failed`), and is `null` on the natural-exit
    /// path where no soft stop is attempted.
    CleanupFinished {
        remaining: usize,
        remaining_pids: Vec<u32>,
        soft_terminate: Option<&'static str>,
    },
    /// A configured ProcessKit resource limit was exceeded or could not be
    /// applied. Part of the v1 schema so adapters pin its shape now; the runner
    /// exposes no resource-limit knobs yet, so it is not emitted at runtime today
    /// (see `docs/schema.md`, "limit_hit").
    // Reserved for when resource-limit configuration lands; constructed by the
    // golden test, so it is otherwise never built in this build.
    #[allow(dead_code)]
    LimitHit {
        /// Which limit was hit, e.g. `processes` / `memory` / `cpu`.
        limit: String,
        detail: Option<String>,
    },
    /// The `--timeout` deadline elapsed while the child was still running. The
    /// teardown it triggers is described by the following cleanup events.
    Timeout {
        timeout_ms: u64,
        grace_ms: Option<u64>,
    },
    /// The run was cancelled and torn down through the shared soft-stop → grace →
    /// hard-kill path. `source` names the trigger: `ctrl_c` for a local `Ctrl-C`, or
    /// `control_cancel` for a `cancel` command that reached the live runner over its
    /// control plane (`docs/schema.md`, "cancelled"). Both share this event because
    /// they share the teardown; the `source` tells them apart (and the terminal
    /// `runner_exit` carries the matching reserved code — `CANCELLED` vs
    /// `CONTROL_CANCELLED`).
    Cancelled {
        source: &'static str,
        grace_ms: Option<u64>,
    },
    /// The run was killed by a control-plane `kill` command: an **immediate** hard
    /// kill of the whole tree with no soft stop and no grace (unlike `cancelled`,
    /// which waits out grace first). `source` is `control_kill`. The teardown it
    /// triggers is described by the following `cleanup_started` / `cleanup_finished`
    /// events; the run's terminal code is the reserved `CONTROL_KILLED` (109). There
    /// is no `grace_ms` field — a kill never waits.
    Killed { source: &'static str },
    /// The program could not be started (not found / not executable / bad cwd):
    /// the child never ran. `code` is the runner-band exit code (`SPAWN`).
    SpawnFailed { code: u8, message: String },
    /// Creating the container, joining the child to it, or handing the terminal to
    /// an interactive child failed. `phase` is `create` (the group could not be
    /// created), `attach` (the launch into the group failed for a non-spawn reason),
    /// or `foreground` (the interactive terminal-foreground handoff failed after the
    /// child had already spawned). `code` is the runner-band exit code (`BACKEND`).
    ContainerFailed {
        phase: &'static str,
        code: u8,
        message: String,
    },
    /// The terminal event of every run: the exact code the runner process returns.
    /// Always emitted — including on the runner's own failure — so a child's code
    /// is never lost or aliased (`AGENTS.md`, "Exit-code fidelity"). `source`
    /// names why the runner exited (`child_exit` | `timeout` | `cancelled` |
    /// `control_cancel` | `control_kill` | `spawn_error` | `container_error` |
    /// `internal` | `setup`); `child_code` carries the child's own code when it
    /// exited on its own, and is `null` for a runner-imposed ending or a child
    /// that never produced one.
    RunnerExit {
        code: i32,
        source: &'static str,
        child_code: Option<i32>,
    },
    /// Bounded stdout/stderr capture (`--capture-dir`) finished: for each stream,
    /// the file it was written to, the full byte counter, the SHA-256 of the
    /// captured bytes, an explicit truncation flag, and an explicit write-error flag
    /// (see [`CaptureInfo`] and `docs/schema.md`, "output_captured"). Emitted **only**
    /// when `--capture-dir`
    /// is set — a run without capture is byte-for-byte unchanged — once per run,
    /// after the teardown pair and before `runner_exit`.
    OutputCaptured {
        stdout: CaptureInfo,
        stderr: CaptureInfo,
    },
}

/// One entry of a [`Event::MembersSnapshot`]. Only `pid` is populated today; the
/// enriched fields are declared for the schema but filled `null` until ProcessKit
/// ships `members_info()` (module docs).
///
/// `Deserialize` as well as `Serialize`: the same PID-only member shape is reused
/// by the control-plane `inspect` snapshot ([`crate::control::Snapshot`]), whose
/// client parses the response back — so the two "container member" views never
/// drift.
#[derive(Debug, Serialize, Deserialize)]
pub struct Member {
    pub pid: u32,
    pub ppid: Option<u32>,
    pub name: Option<String>,
    pub start_time: Option<String>,
}

impl Member {
    /// A member built from a bare PID: every enriched field is explicitly absent.
    pub fn from_pid(pid: u32) -> Self {
        Self {
            pid,
            ppid: None,
            name: None,
            start_time: None,
        }
    }
}

/// One stream's bounded-capture result, as carried by [`Event::OutputCaptured`].
///
/// `bytes` is the **full** byte counter — every decoded byte the stream produced,
/// so it exceeds the file's size once the stream was truncated or a write failed.
/// `sha256` is the lowercase-hex digest of the bytes actually written to `path` (so
/// a consumer can verify the file it holds), computed with the same [`crate::hash`]
/// primitive as the argv fingerprint. `truncated` and `write_error` are two
/// **explicit** flags, never inferred from the file's size, that between them tell a
/// consumer whether the file is the whole stream: `truncated` is set when the stream
/// outran the per-stream capture ceiling and the tail was deliberately dropped;
/// `write_error` is set when a file write failed mid-stream (a disk problem), after
/// which capture stopped touching the broken file. The two are independent — a stream
/// can be both — so "captured in full" is `!truncated && !write_error`, and each
/// incomplete cause is distinguishable from the other on the flags alone
/// (`docs/schema.md`, "output_captured").
#[derive(Debug, Serialize)]
pub struct CaptureInfo {
    path: String,
    bytes: u64,
    sha256: String,
    truncated: bool,
    write_error: bool,
}

impl CaptureInfo {
    /// Assemble one stream's capture metadata for the event.
    pub fn new(
        path: String,
        bytes: u64,
        sha256: String,
        truncated: bool,
        write_error: bool,
    ) -> Self {
        Self {
            path,
            bytes,
            sha256,
            truncated,
            write_error,
        }
    }

    /// The full byte counter (every produced byte, past the ceiling too).
    #[cfg(test)]
    pub fn bytes(&self) -> u64 {
        self.bytes
    }

    /// The lowercase-hex SHA-256 of the captured (written) bytes.
    #[cfg(test)]
    pub fn sha256(&self) -> &str {
        &self.sha256
    }

    /// Whether the stream outran the capture ceiling.
    #[cfg(test)]
    pub fn truncated(&self) -> bool {
        self.truncated
    }

    /// Whether a file write failed mid-stream, leaving the on-disk transcript short
    /// of the byte counter.
    #[cfg(test)]
    pub fn write_error(&self) -> bool {
        self.write_error
    }
}

/// The command a run executed, in its redaction-aware v1 shape. `redacted` is
/// `true` by default and `false` only under `--argv-raw`; `argv` carries the raw
/// argv strings only when not redacted. `argv_sha256` (a one-way fingerprint) and
/// `hint` (a worker-shape category, or `null` when unrecognized) are filled on
/// every run — they never expose the command line — so redaction never blinds a
/// consumer to *which* run it is looking at (see [`argv_sha256_hex`],
/// [`classify_hint`], and `docs/schema.md`, "Command redaction").
#[derive(Debug, Serialize)]
pub struct CommandInfo {
    redacted: bool,
    argv: Option<Vec<String>>,
    argv_sha256: Option<String>,
    hint: Option<String>,
}

impl CommandInfo {
    /// Build the command field for `argv`. The one-way `argv_sha256` fingerprint
    /// and the worker-shape `hint` are always computed — neither can leak the
    /// command line — so they are present whether or not the raw argv is recorded.
    /// `argv_raw` additionally records the raw argv array verbatim; without it the
    /// argv is omitted (redacted) and only the fingerprint and hint remain.
    pub fn for_argv<I, S>(argv: I, argv_raw: bool) -> Self
    where
        I: IntoIterator<Item = S>,
        S: AsRef<std::ffi::OsStr>,
    {
        // Render argv once to the lossy-UTF-8 strings that `--argv-raw` would
        // record and the classifier inspects, then derive the fingerprint and hint
        // from that single rendering. Only the raw array is gated behind the flag;
        // the redaction-safe fields are computed unconditionally.
        let strings: Vec<String> = argv
            .into_iter()
            .map(|a| a.as_ref().to_string_lossy().into_owned())
            .collect();
        let argv_sha256 = Some(argv_sha256_hex(&strings));
        let hint = classify_hint(&strings).map(str::to_string);
        Self {
            redacted: !argv_raw,
            argv: argv_raw.then_some(strings),
            argv_sha256,
            hint,
        }
    }
}

/// The hex SHA-256 fingerprint of a run's argv: the lossy-UTF-8 argv elements
/// joined by a single NUL byte — a byte that cannot occur inside a real argv
/// element on any platform, so element boundaries stay unambiguous — then hashed.
/// This canonical encoding is documented in `docs/schema.md` ("Command redaction")
/// so an adapter that re-emits the schema reproduces the exact digest. The hash is
/// one-way, so it fingerprints a command without disclosing it. The digest itself
/// is [`crate::hash::sha256_hex`], the same primitive the bounded output capture
/// hashes with (`docs/schema.md`, "Fingerprint").
fn argv_sha256_hex(argv: &[String]) -> String {
    crate::hash::sha256_hex(argv.join("\0").as_bytes())
}

/// One worker-shape classifier rule: the `hint` it emits and the set of substrings
/// that must **all** be present in a run's argv for it to match.
struct HintRule {
    /// The `hint` value emitted when every marker below is found in the argv.
    hint: &'static str,
    /// Substrings that must all appear (case-insensitively) in the argv. Stored in
    /// their readable, documented form; matching lowercases both sides.
    markers: &'static [&'static str],
}

/// The worker-shape hint catalog: plain, ordered data rather than branch logic, so
/// a new shape is one new entry here — and the same table is mirrored in
/// `docs/schema.md`, keeping the catalog visible outside the code. The first rule
/// whose markers all match wins; an argv matching none yields `null`.
///
/// Seed entry — **MSBuild reusable worker nodes.** A build host keeps long-lived
/// `MSBuild.dll` worker processes around (`/nodemode:1 /nodeReuse:true`); they are
/// a classic "stuck after the build" tree. Tagging the shape lets a consumer (the
/// orchestrator) name such a node without its full, possibly secret-bearing
/// command line.
static HINT_RULES: &[HintRule] = &[HintRule {
    hint: "msbuild_node_reuse",
    markers: &["MSBuild.dll", "/nodemode:1", "/nodeReuse:true"],
}];

/// Classify a run's argv against [`HINT_RULES`], returning the first matching
/// rule's `hint` or `None` when no shape is recognized (the common case). Matching
/// is a case-insensitive substring test over the space-joined argv, so a marker is
/// found whether it is a whole argument or embedded in one (e.g. a full
/// `…/MSBuild.dll` path). The hint is a fixed category label — never argv content —
/// so emitting it does not weaken redaction.
fn classify_hint(argv: &[String]) -> Option<&'static str> {
    let haystack = argv.join(" ").to_ascii_lowercase();
    HINT_RULES
        .iter()
        .find(|rule| {
            rule.markers
                .iter()
                .all(|marker| haystack.contains(marker.to_ascii_lowercase().as_str()))
        })
        .map(|rule| rule.hint)
}

/// Append-only writer for a run's JSONL event stream.
///
/// Each event is written as one line and **flushed immediately**: the runner
/// forwards a completed child's code via [`std::process::exit`], which skips
/// destructors, so a buffered event (including the terminal `runner_exit`) would
/// be lost without a per-event flush. A write failure after the stream is open is
/// best-effort — it warns once on stderr and drops subsequent events rather than
/// aborting an otherwise-healthy run (the child's exit-code fidelity outranks
/// diagnostics); the fail-closed check is at [`Emitter::create`], before the child
/// is ever spawned.
pub struct Emitter {
    file: std::fs::File,
    poisoned: bool,
}

impl Emitter {
    /// Open (creating or truncating) the JSONL file for this run. Fails if the
    /// path cannot be created — the caller treats that as a runner-own failure and
    /// never spawns the child, so no child code can be lost to a logging setup
    /// error.
    pub fn create(path: &Path) -> std::io::Result<Self> {
        let file = std::fs::File::create(path)?;
        Ok(Self {
            file,
            poisoned: false,
        })
    }

    /// Emit one event, stamped with the current time. Infallible by contract: a
    /// write error is reported once to stderr and then swallowed (see the type
    /// docs), so lifecycle wiring never has to branch on logging failure.
    pub fn emit(&mut self, event: &Event) {
        if self.poisoned {
            return;
        }
        let line = match serialize_record(event, now_rfc3339()) {
            Ok(line) => line,
            Err(err) => {
                // A struct with string keys and no I/O cannot fail to serialize;
                // treat the impossible as best-effort rather than panicking.
                self.poison(format_args!("could not serialize a JSONL event: {err}"));
                return;
            }
        };
        if let Err(err) = self
            .file
            .write_all(line.as_bytes())
            .and_then(|()| self.file.write_all(b"\n"))
            .and_then(|()| self.file.flush())
        {
            self.poison(format_args!("could not write a JSONL event: {err}"));
        }
    }

    /// Warn once, then silence further events. Keeps a broken log from spamming
    /// stderr while still surfacing the first failure honestly.
    fn poison(&mut self, reason: std::fmt::Arguments<'_>) {
        eprintln!("processkit-cli: warning: JSONL event logging disabled: {reason}");
        self.poisoned = true;
    }
}

/// Serialize one enveloped event to a compact single-line JSON string (no trailing
/// newline). Separated from [`Emitter::emit`] so tests can render with a fixed
/// timestamp for the golden fixture.
fn serialize_record(event: &Event, time: String) -> serde_json::Result<String> {
    serde_json::to_string(&Record {
        schema_version: SCHEMA_VERSION,
        time,
        event,
    })
}

/// The run identifier for this run: the explicit `--run-id` when given, otherwise
/// a generated value unique per invocation on this host (`run-<pid>-<unix_nanos>`).
pub fn resolve_run_id(explicit: Option<&str>) -> String {
    match explicit {
        Some(id) => id.to_string(),
        None => {
            let nanos = SystemTime::now()
                .duration_since(SystemTime::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0);
            format!("run-{}-{nanos}", std::process::id())
        }
    }
}

/// The stable schema string for a containment [`Mechanism`]. `Mechanism` is
/// `#[non_exhaustive]`, so an unknown future variant maps to `"unknown"` rather
/// than a guess.
pub fn mechanism_str(mechanism: Mechanism) -> &'static str {
    match mechanism {
        Mechanism::JobObject => "job_object",
        Mechanism::CgroupV2 => "cgroup_v2",
        Mechanism::ProcessGroup => "process_group",
        _ => "unknown",
    }
}

/// The containment guarantee that survives an abrupt runner death on this target.
/// This is deliberately OS-derived rather than inferred from [`Mechanism`]: Linux
/// cgroups persist after their creator dies, so the enabled PDEATHSIG still covers
/// only the direct child; a Windows Job handle close reaps the whole tree.
///
/// Sourced from `processkit`'s own honest capability report
/// (`Command::kill_on_parent_death_scope`, shipped in processkit 2.3.2) rather than
/// reimplementing the per-platform `cfg!` derivation here, so this crate and
/// `processkit` cannot drift on the claim. `ParentDeathCleanup` is
/// `#[non_exhaustive]`; an unrecognized future variant maps to `"none"` — the
/// conservative choice, since this string is a reaping *guarantee*, not a mere
/// capability label, and must never overclaim.
pub fn abrupt_cleanup_str() -> &'static str {
    match PkCommand::kill_on_parent_death_scope() {
        ParentDeathCleanup::WholeTree => "whole_tree",
        ParentDeathCleanup::DirectChildOnly => "direct_child_only",
        ParentDeathCleanup::Unsupported => "none",
        _ => "none",
    }
}

/// Decompose a completed run's [`Outcome`] into the `root_exited` fields:
/// `(outcome, code, signal)`. `Outcome` is `#[non_exhaustive]`; an unrecognized
/// variant is reported as `"unknown"` with neither a code nor a signal.
pub fn outcome_fields(outcome: &Outcome) -> (&'static str, Option<i32>, Option<i32>) {
    match outcome {
        Outcome::Exited(code) => ("exited", Some(*code), None),
        Outcome::Signalled(Some(signal)) => ("signalled", None, Some(*signal)),
        Outcome::Signalled(None) => ("signalled", None, None),
        Outcome::TimedOut => ("timed_out", None, None),
        _ => ("unknown", None, None),
    }
}

/// The current time formatted for the event envelope.
fn now_rfc3339() -> String {
    format_rfc3339_utc(SystemTime::now())
}

/// Format a [`SystemTime`] as RFC 3339 UTC with millisecond precision
/// (`YYYY-MM-DDTHH:MM:SS.sssZ`). Hand-rolled to avoid a date-library dependency
/// for a single field; the civil-date conversion is Howard Hinnant's standard
/// `civil_from_days` algorithm (validated in [`tests::timestamp_matches_known_vectors`]).
///
/// `pub(crate)` so the run registry ([`crate::registry`]) stamps its record's
/// `started_at` with the same formatter rather than duplicating the civil-date math.
pub(crate) fn format_rfc3339_utc(time: SystemTime) -> String {
    let dur = time
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or(Duration::ZERO);
    let secs = dur.as_secs() as i64;
    let millis = dur.subsec_millis();

    let days = secs.div_euclid(86_400);
    let secs_of_day = secs.rem_euclid(86_400);
    let (hour, minute, second) = (
        secs_of_day / 3_600,
        (secs_of_day % 3_600) / 60,
        secs_of_day % 60,
    );
    let (year, month, day) = civil_from_days(days);
    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}.{millis:03}Z")
}

/// Convert a count of days since the Unix epoch (1970-01-01) into a
/// `(year, month, day)` civil date — Howard Hinnant's `civil_from_days`
/// (<http://howardhinnant.github.io/date_algorithms.html>), valid across the full
/// proleptic Gregorian range.
fn civil_from_days(days: i64) -> (i64, u32, u32) {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097; // [0, 146096]
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365; // [0, 399]
    let year = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153; // [0, 11]
    let day = (doy - (153 * mp + 2) / 5 + 1) as u32; // [1, 31]
    let month = if mp < 10 { mp + 3 } else { mp - 9 } as u32; // [1, 12]
    let year = year + i64::from(month <= 2);
    (year, month, day)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// A fixed timestamp for deterministic golden rendering, produced by the real
    /// formatter so the fixture also pins the timestamp shape.
    fn fixed_time() -> String {
        format_rfc3339_utc(SystemTime::UNIX_EPOCH + Duration::from_millis(1_700_000_000_123))
    }

    /// One representative instance of every event variant, in lifecycle order — the
    /// sample stream captured by the golden fixture. `run_started` appears twice on
    /// purpose: once redacted-by-default and once under `--argv-raw`, so the fixture
    /// pins **both** command-redaction branches — and shows that the `argv_sha256`
    /// fingerprint and the `hint` are identical either way (they never depend on
    /// whether the raw argv is disclosed).
    fn sample_events() -> Vec<Event> {
        // An MSBuild reusable-worker argv: a recognized worker shape, so the fixture
        // also demonstrates a populated `hint` next to the fingerprint.
        let msbuild_argv = [
            "C:\\Program Files\\dotnet\\sdk\\MSBuild.dll",
            "/nodemode:1",
            "/nodeReuse:true",
        ];
        vec![
            Event::RunStarted {
                run_id: "run-000".to_string(),
                root_pid: Some(4242),
                mechanism: mechanism_str(Mechanism::JobObject),
                abrupt_cleanup: "whole_tree",
                cwd: Some("/work/project".to_string()),
                command: CommandInfo::for_argv(msbuild_argv, false),
            },
            Event::RunStarted {
                run_id: "run-001".to_string(),
                root_pid: Some(4242),
                mechanism: mechanism_str(Mechanism::JobObject),
                abrupt_cleanup: "whole_tree",
                cwd: Some("/work/project".to_string()),
                command: CommandInfo::for_argv(msbuild_argv, true),
            },
            Event::MembersSnapshot {
                members: vec![Member::from_pid(4242), Member::from_pid(4243)],
            },
            Event::RootExited {
                outcome: "exited",
                code: Some(0),
                signal: None,
            },
            Event::CleanupStarted { members_before: 2 },
            Event::CleanupFinished {
                remaining: 0,
                remaining_pids: vec![],
                soft_terminate: None,
            },
            // One `output_captured`: stdout captured in full (the `abc` vector),
            // stderr empty (the empty-string digest). Both complete — neither
            // ceiling-truncated nor write-errored. Pins the shape adapters read when
            // `--capture-dir` is set; a run without capture emits none.
            Event::OutputCaptured {
                stdout: CaptureInfo::new(
                    "/work/project/capture/stdout.log".to_string(),
                    3,
                    "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad".to_string(),
                    false,
                    false,
                ),
                stderr: CaptureInfo::new(
                    "/work/project/capture/stderr.log".to_string(),
                    0,
                    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855".to_string(),
                    false,
                    false,
                ),
            },
            Event::LimitHit {
                limit: "processes".to_string(),
                detail: Some("exceeded the 64-process cap".to_string()),
            },
            Event::Timeout {
                timeout_ms: 5_000,
                grace_ms: Some(2_000),
            },
            Event::Cancelled {
                source: "ctrl_c",
                grace_ms: Some(2_000),
            },
            Event::SpawnFailed {
                code: 101,
                message: "could not start the program: program not found".to_string(),
            },
            Event::ContainerFailed {
                phase: "create",
                code: 102,
                message: "could not create the ProcessKit container".to_string(),
            },
            Event::RunnerExit {
                code: 0,
                source: "child_exit",
                child_code: Some(0),
            },
            // Control-plane endings, appended so the existing catalog lines above
            // stay byte-for-byte identical (an additive schema change never rewrites
            // a shipped golden case). `control_cancel` reuses the `cancelled` event
            // with its own trigger; `control_kill` is the dedicated no-grace event.
            Event::Cancelled {
                source: "control_cancel",
                grace_ms: Some(2_000),
            },
            Event::Killed {
                source: "control_kill",
            },
            Event::RunnerExit {
                code: 108,
                source: "control_cancel",
                child_code: None,
            },
            Event::RunnerExit {
                code: 109,
                source: "control_kill",
                child_code: None,
            },
        ]
    }

    fn golden_path() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures/schema/v1/events.jsonl")
    }

    /// Render the sample stream exactly as the emitter would write it (one flushed
    /// line per event, trailing newline included).
    fn render_sample_stream() -> String {
        let time = fixed_time();
        let mut out = String::new();
        for event in sample_events() {
            out.push_str(&serialize_record(&event, time.clone()).expect("event serializes"));
            out.push('\n');
        }
        out
    }

    /// The golden gate (`AGENTS.md`, "Golden-schema tests"): the serialized sample
    /// stream must match the committed fixture byte-for-byte. Set
    /// `UPDATE_SCHEMA_GOLDEN=1` to rewrite the fixture after an intentional,
    /// version-bumped schema change.
    #[test]
    fn golden_stream_matches_the_fixture() {
        let rendered = render_sample_stream();
        if std::env::var_os("UPDATE_SCHEMA_GOLDEN").is_some() {
            std::fs::write(golden_path(), &rendered).expect("rewrite golden fixture");
        }
        let expected = std::fs::read_to_string(golden_path()).unwrap_or_else(|err| {
            panic!(
                "read golden fixture {}: {err}; regenerate with UPDATE_SCHEMA_GOLDEN=1",
                golden_path().display()
            )
        });
        assert_eq!(
            rendered, expected,
            "JSONL schema drift from fixtures/schema/v1/events.jsonl; if intended, bump \
             SCHEMA_VERSION and regenerate with UPDATE_SCHEMA_GOLDEN=1"
        );
    }

    /// The core envelope invariant: every event carries `schema_version` and a
    /// snake_case `event` type tag.
    #[test]
    fn every_event_carries_schema_version_and_a_type_tag() {
        for event in sample_events() {
            let line = serialize_record(&event, fixed_time()).expect("serializes");
            let value: serde_json::Value = serde_json::from_str(&line).expect("valid JSON");
            assert_eq!(
                value["schema_version"], 1,
                "every event must carry schema_version=1: {line}"
            );
            assert!(
                value.get("event").and_then(|v| v.as_str()).is_some(),
                "every event must carry a string `event` tag: {line}"
            );
        }
    }

    /// A member built from a bare PID declares the enriched fields but marks each
    /// explicitly absent (JSON `null`) — never omitted, never invented.
    #[test]
    fn members_enriched_fields_are_present_but_null_from_bare_pids() {
        let member = Member::from_pid(4242);
        assert_eq!(member.pid, 4242);
        assert!(member.ppid.is_none() && member.name.is_none() && member.start_time.is_none());

        let line = serialize_record(
            &Event::MembersSnapshot {
                members: vec![Member::from_pid(4242)],
            },
            fixed_time(),
        )
        .expect("serializes");
        let value: serde_json::Value = serde_json::from_str(&line).expect("valid JSON");
        let member = &value["members"][0];
        assert_eq!(member["pid"], 4242);
        for field in ["ppid", "name", "start_time"] {
            assert!(
                member.get(field).map(|v| v.is_null()).unwrap_or(false),
                "enriched field `{field}` must be present and null: {line}"
            );
        }
    }

    /// Whether `s` is a 64-character lowercase-hex string — the shape of an
    /// `argv_sha256` fingerprint.
    fn is_sha256_hex(s: Option<&str>) -> bool {
        matches!(s, Some(s) if s.len() == 64 && s.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f')))
    }

    /// Redacted-by-default vs `--argv-raw`, and the redaction-safe fields filled
    /// either way. A bare run omits the raw argv but still carries the fingerprint
    /// (and a `hint` when the shape is recognized); `--argv-raw` adds the raw argv
    /// without changing the fingerprint or the hint.
    #[test]
    fn command_info_redacts_by_default_and_honors_argv_raw() {
        // A non-worker argv: redacted, fingerprinted, no recognized hint.
        let redacted = CommandInfo::for_argv(["cmd", "/c", "secret"], false);
        assert!(redacted.redacted && redacted.argv.is_none());
        assert!(
            is_sha256_hex(redacted.argv_sha256.as_deref()),
            "a redacted command still carries a hex fingerprint: {:?}",
            redacted.argv_sha256
        );
        assert!(
            redacted.hint.is_none(),
            "an unrecognized shape has no hint: {:?}",
            redacted.hint
        );

        // `--argv-raw` records the raw argv while keeping the same fingerprint/hint.
        let raw = CommandInfo::for_argv(["cmd", "/c", "secret"], true);
        assert!(!raw.redacted);
        assert_eq!(
            raw.argv.as_deref(),
            Some(["cmd", "/c", "secret"].map(String::from).as_slice())
        );
        assert_eq!(
            raw.argv_sha256, redacted.argv_sha256,
            "the fingerprint does not depend on whether the raw argv is disclosed"
        );
        assert_eq!(raw.hint, redacted.hint);
    }

    /// The argv fingerprint is SHA-256 over the NUL-joined argv: a single-element
    /// argv hashes exactly its one element (no separator), and the NUL boundary
    /// keeps element splits significant so distinct argvs cannot collide.
    #[test]
    fn argv_fingerprint_is_canonical_and_boundary_sensitive() {
        // One element: the join adds no separator, so it equals SHA-256("abc").
        assert_eq!(
            argv_sha256_hex(&["abc".to_string()]),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        // The NUL separator makes element boundaries significant: ["a","b"] and
        // ["ab"] are different argvs and must not fingerprint alike.
        assert_ne!(
            argv_sha256_hex(&["a".to_string(), "b".to_string()]),
            argv_sha256_hex(&["ab".to_string()])
        );
    }

    /// The hint classifier tags an MSBuild reusable-worker argv (case-insensitively,
    /// wherever the markers sit) and leaves everything else unclassified.
    #[test]
    fn classify_hint_recognizes_msbuild_and_ignores_unknown() {
        let msbuild = [
            "C:\\dotnet\\MSBuild.dll".to_string(),
            "/nodemode:1".to_string(),
            "/nodeReuse:true".to_string(),
        ];
        assert_eq!(classify_hint(&msbuild), Some("msbuild_node_reuse"));

        // Case-insensitive: a lowercased argv still matches.
        let lowercased = [
            "msbuild.dll".to_string(),
            "/nodemode:1".to_string(),
            "/nodereuse:true".to_string(),
        ];
        assert_eq!(classify_hint(&lowercased), Some("msbuild_node_reuse"));

        // Missing one marker → no match.
        let partial = ["MSBuild.dll".to_string(), "/nodemode:1".to_string()];
        assert_eq!(classify_hint(&partial), None);

        // An ordinary command is unclassified.
        assert_eq!(
            classify_hint(&["cmd".to_string(), "/c".to_string(), "build".to_string()]),
            None
        );
    }

    // Property-based tier (T-167). Placed in this same `#[cfg(test)]` module
    // rather than a new `tests/properties.rs`: `classify_hint`/`HINT_RULES` are
    // private to this module, so an integration test under `tests/` — which links
    // only against the crate's public surface — cannot reach them; only an
    // in-crate unit test can. These run under the library unit-test tier (a plain
    // `cargo test`, i.e. `--lib`).
    //
    // The generator is deliberately *not* fully random bytes: `classify_hint` is
    // a documented, rule-driven substring matcher (`HINT_RULES`), so a
    // meaningful property test constructs argv from the documented marker set
    // (with randomized casing and optional omission) interleaved with filler
    // tokens drawn from a pool that cannot spell out any marker substring —
    // exercising the classifier's actual contract instead of noise it was never
    // meant to classify.
    mod proptests {
        use super::*;
        use proptest::prelude::*;

        /// The one documented rule's markers, canonical casing.
        const MARKERS: [&str; 3] = ["MSBuild.dll", "/nodemode:1", "/nodeReuse:true"];

        /// Filler tokens that share no substring with any marker above (verified
        /// by the `debug_assert!` below), so their presence never accidentally
        /// satisfies a marker match.
        const FILLERS: [&str; 8] = [
            "cmd", "/c", "echo", "true", "hello", "value123", "--flag", "worker",
        ];

        /// Re-case `s` per `variant`: 0 = as written, 1 = upper, 2 = lower.
        fn recase(s: &str, variant: u8) -> String {
            match variant % 3 {
                0 => s.to_string(),
                1 => s.to_uppercase(),
                _ => s.to_lowercase(),
            }
        }

        proptest! {
            #![proptest_config(ProptestConfig::with_cases(256))]

            /// Classifying the same argv twice is deterministic (repeated calls
            /// agree), and the outcome matches the documented rule: the hint fires
            /// exactly when all three markers are present (in any casing), and
            /// never fires on the filler-only pool, which cannot spell out a
            /// marker substring.
            #[test]
            fn classification_is_stable_and_matches_the_documented_rule(
                include in [any::<bool>(), any::<bool>(), any::<bool>()],
                casing in [0u8..3, 0u8..3, 0u8..3],
                fillers in prop::collection::vec(
                    prop::sample::select(FILLERS.as_slice()),
                    0..4,
                ),
                shuffle_seed in any::<u64>(),
            ) {
                for marker in MARKERS {
                    for filler in FILLERS {
                        debug_assert!(
                            !filler.to_ascii_lowercase().contains(&marker.to_ascii_lowercase()),
                            "filler {filler:?} must not contain marker {marker:?}"
                        );
                    }
                }

                let mut argv: Vec<String> = MARKERS
                    .iter()
                    .zip(include)
                    .zip(casing)
                    .filter(|((_, keep), _)| *keep)
                    .map(|((marker, _), variant)| recase(marker, variant))
                    .collect();
                argv.extend(fillers.iter().map(|f| f.to_string()));

                // A cheap deterministic shuffle (no extra proptest strategy needed):
                // rotate the vector by the seed. Order must not affect the result —
                // classify_hint checks substring presence, not position.
                if !argv.is_empty() {
                    let rotate_by = (shuffle_seed as usize) % argv.len();
                    argv.rotate_left(rotate_by);
                }

                let first = classify_hint(&argv);
                let second = classify_hint(&argv);
                prop_assert_eq!(first, second, "classification must be stable across repeated calls");

                let all_present = include.iter().all(|&keep| keep);
                if all_present {
                    prop_assert_eq!(first, Some("msbuild_node_reuse"));
                } else {
                    prop_assert_eq!(first, None);
                }
            }
        }
    }

    #[test]
    fn mechanism_maps_to_the_documented_strings() {
        assert_eq!(mechanism_str(Mechanism::JobObject), "job_object");
        assert_eq!(mechanism_str(Mechanism::CgroupV2), "cgroup_v2");
        assert_eq!(mechanism_str(Mechanism::ProcessGroup), "process_group");
    }

    #[test]
    fn outcome_fields_split_code_from_signal() {
        assert_eq!(
            outcome_fields(&Outcome::Exited(7)),
            ("exited", Some(7), None)
        );
        assert_eq!(
            outcome_fields(&Outcome::Signalled(Some(9))),
            ("signalled", None, Some(9))
        );
        assert_eq!(
            outcome_fields(&Outcome::Signalled(None)),
            ("signalled", None, None)
        );
        assert_eq!(
            outcome_fields(&Outcome::TimedOut),
            ("timed_out", None, None)
        );
    }

    /// `runner_exit` keeps the child's own code in `child_code` even though `code`
    /// is what the process returns — the "child code is never lost" contract in
    /// its machine form.
    #[test]
    fn runner_exit_preserves_the_child_code_separately() {
        let child = Event::RunnerExit {
            code: 7,
            source: "child_exit",
            child_code: Some(7),
        };
        let value: serde_json::Value =
            serde_json::from_str(&serialize_record(&child, fixed_time()).unwrap()).unwrap();
        assert_eq!(value["code"], 7);
        assert_eq!(value["child_code"], 7);
        assert_eq!(value["source"], "child_exit");

        // A runner-imposed ending forwards a runner-band code and no child code.
        let timeout = Event::RunnerExit {
            code: 106,
            source: "timeout",
            child_code: None,
        };
        let value: serde_json::Value =
            serde_json::from_str(&serialize_record(&timeout, fixed_time()).unwrap()).unwrap();
        assert_eq!(value["code"], 106);
        assert!(value["child_code"].is_null());
    }

    /// The control-plane endings are distinguishable in the stream. A control-plane
    /// `cancel` reuses the `cancelled` event but carries its own `source`
    /// (`control_cancel`, not `ctrl_c`); a `kill` is the dedicated `killed` event
    /// with `source` `control_kill` and no `grace_ms` (a kill never waits). The
    /// terminal `runner_exit` for each carries the matching reserved code.
    #[test]
    fn control_plane_endings_are_distinguishable_in_the_stream() {
        // A control cancel is a `cancelled` event, told apart from a Ctrl-C by source.
        let cancel = Event::Cancelled {
            source: "control_cancel",
            grace_ms: Some(2_000),
        };
        let value: serde_json::Value =
            serde_json::from_str(&serialize_record(&cancel, fixed_time()).unwrap()).unwrap();
        assert_eq!(value["event"], "cancelled");
        assert_eq!(
            value["source"], "control_cancel",
            "a control-plane cancel is not a Ctrl-C: {value}"
        );

        // A kill is its own event: no grace field, its own source.
        let kill = Event::Killed {
            source: "control_kill",
        };
        let value: serde_json::Value =
            serde_json::from_str(&serialize_record(&kill, fixed_time()).unwrap()).unwrap();
        assert_eq!(value["event"], "killed");
        assert_eq!(value["source"], "control_kill");
        assert!(
            value.get("grace_ms").is_none(),
            "a kill has no grace window: {value}"
        );

        // The terminal events carry the distinct reserved codes with no child code.
        for (source, code) in [("control_cancel", 108), ("control_kill", 109)] {
            let exit = Event::RunnerExit {
                code,
                source,
                child_code: None,
            };
            let value: serde_json::Value =
                serde_json::from_str(&serialize_record(&exit, fixed_time()).unwrap()).unwrap();
            assert_eq!(value["code"], code);
            assert_eq!(value["source"], source);
            assert!(value["child_code"].is_null());
        }
    }

    /// `output_captured` carries per-stream capture metadata: a file path, the full
    /// byte counter, the content digest, and the two explicit incompleteness flags
    /// (`truncated`, `write_error`) as real booleans. The two streams show the flags
    /// are independent: stdout was ceiling-truncated with no disk error, stderr hit a
    /// mid-stream write error without ever reaching the ceiling.
    #[test]
    fn output_captured_reports_per_stream_metadata() {
        let event = Event::OutputCaptured {
            stdout: CaptureInfo::new(
                "/tmp/cap/stdout.log".to_string(),
                9000,
                "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad".to_string(),
                true,
                false,
            ),
            stderr: CaptureInfo::new(
                "/tmp/cap/stderr.log".to_string(),
                50,
                "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855".to_string(),
                false,
                true,
            ),
        };
        let value: serde_json::Value =
            serde_json::from_str(&serialize_record(&event, fixed_time()).unwrap()).unwrap();
        assert_eq!(value["event"], "output_captured");
        assert_eq!(value["stdout"]["path"], "/tmp/cap/stdout.log");
        assert_eq!(value["stdout"]["bytes"], 9000);
        assert!(is_sha256_hex(value["stdout"]["sha256"].as_str()));
        assert_eq!(
            value["stdout"]["truncated"], true,
            "an over-ceiling stream is explicitly truncated"
        );
        assert_eq!(
            value["stdout"]["write_error"], false,
            "a clean ceiling clip is not a write error"
        );
        // The sibling stream is independent: a mid-stream write error, so its byte
        // counter (50) outruns what reached disk, and it is flagged distinctly from a
        // ceiling truncation.
        assert_eq!(value["stderr"]["bytes"], 50);
        assert_eq!(value["stderr"]["truncated"], false);
        assert_eq!(
            value["stderr"]["write_error"], true,
            "a mid-stream disk write failure is its own explicit flag"
        );
    }

    /// The hand-rolled UTC formatter against well-known epoch instants.
    #[test]
    fn timestamp_matches_known_vectors() {
        let at = |secs: u64| format_rfc3339_utc(SystemTime::UNIX_EPOCH + Duration::from_secs(secs));
        assert_eq!(at(0), "1970-01-01T00:00:00.000Z");
        assert_eq!(at(86_400), "1970-01-02T00:00:00.000Z");
        // The classic Unix "billennium".
        assert_eq!(at(1_000_000_000), "2001-09-09T01:46:40.000Z");
        assert_eq!(at(1_609_459_200), "2021-01-01T00:00:00.000Z");
        // Millisecond precision is preserved.
        assert_eq!(
            format_rfc3339_utc(SystemTime::UNIX_EPOCH + Duration::from_millis(1_609_459_200_123)),
            "2021-01-01T00:00:00.123Z"
        );
    }
}
