//! The versioned JSONL lifecycle-event schema and its emitter.
//!
//! This module owns processkit-cli's **normative event contract** (`AGENTS.md`,
//! "This repository owns the normative JSONL schema"): every event is one JSON
//! object on its own line, carrying a `schema_version`, written only to the
//! `--jsonl` file — never to stdout, so the child's stream stays pristine
//! (`AGENTS.md`, "Streams are strictly separated"). Adapters (processkit-py's
//! CLI) pin `schema_version` and reimplement these shapes, so the field set here
//! is a public API: `docs/schema.md` is the human-readable normative document and
//! `fixtures/schema/v1/events.jsonl` is the golden material adapters test against
//! (regenerated by [`tests::golden_stream_matches_the_fixture`]).
//!
//! Two field groups are shaped to keep the wire form stable as capabilities grow:
//!
//! - **Enriched member fields (still reserved).** ProcessKit's public API returns
//!   bare PIDs today; the richer per-member snapshot (`ppid` / executable `name` /
//!   `start_time`) is a filed-but-unshipped ProcessKit-rs capability
//!   (`ProcessGroup::members_info()`). So [`Member`] declares those fields as
//!   optional and the emitter fills them from bare PIDs alone, marking every
//!   richer field explicitly **absent** (JSON `null`) rather than inventing a
//!   local process-enumeration path (`AGENTS.md`, "Build strictly on the public
//!   `processkit` API").
//! - **Command line / argv redaction (shipped in T-005).** Command lines carry
//!   secrets, so argv is redacted by default (`AGENTS.md`, "Argv is redacted by
//!   default"): a redacted `command` omits the raw `argv` and instead carries a
//!   one-way SHA-256 fingerprint of argv (`argv_sha256`) plus, for recognized
//!   worker shapes, a categorical `hint` (see [`HINT_RULES`]). Neither can reveal
//!   the command line, so both are filled on **every** run; `--argv-raw` only adds
//!   the raw `argv` array on top. Populating these once-reserved fields does not
//!   change the event's wire shape.

use std::io::Write;
use std::path::Path;
use std::time::{Duration, SystemTime};

use serde::Serialize;

use processkit::{Mechanism, Outcome};

/// The schema version stamped on every event. Part of the compatibility surface:
/// any breaking change to an event's shape is a **major** bump of this number
/// (`docs/schema.md`, "Versioning").
pub const SCHEMA_VERSION: u32 = 1;

/// The wire record actually serialized per line: the common envelope
/// (`schema_version`, `time`) plus the flattened event body (its `event` type tag
/// and payload). Field order here is the on-the-wire order and is stable.
#[derive(Serialize)]
struct Record<'a> {
    schema_version: u32,
    /// Emission time, RFC 3339 UTC with millisecond precision. For `root_exited`
    /// this doubles as the required exit timestamp — the moment the runner
    /// observed the child leave.
    time: String,
    #[serde(flatten)]
    event: &'a Event,
}

/// One lifecycle event. Internally tagged (`"event": "<snake_case>"`) so each line
/// is self-describing; every variant is documented in `docs/schema.md`.
#[derive(Debug, Serialize)]
#[serde(tag = "event", rename_all = "snake_case")]
pub enum Event {
    /// The run has started: the child is spawned into the container and its root
    /// PID, the containment mechanism, the working directory, and the (redacted)
    /// command are known.
    RunStarted {
        run_id: String,
        /// The root child's PID. `null` if the backend did not expose one.
        root_pid: Option<u32>,
        /// `job_object` | `cgroup_v2` | `process_group` (see [`mechanism_str`]).
        mechanism: &'static str,
        /// Working directory the child runs in, or `null` if it could not be
        /// resolved.
        cwd: Option<String>,
        command: CommandInfo,
    },
    /// A point-in-time snapshot of the container's members. PID-only today; the
    /// richer fields are declared but absent (see module docs and [`Member`]).
    MembersSnapshot { members: Vec<Member> },
    /// The root child exited on its own. `code` is set for a normal exit; `signal`
    /// for a Unix signal death; both `null` only for an outcome without either.
    RootExited {
        /// `exited` | `signalled` | `timed_out` | `unknown` (see [`outcome_fields`]).
        outcome: &'static str,
        code: Option<i32>,
        signal: Option<i32>,
    },
    /// Container teardown is beginning; `members_before` is the tree size about to
    /// be reaped.
    CleanupStarted { members_before: usize },
    /// Container teardown finished. `remaining_pids` is a post-hard-kill snapshot
    /// (empty on the Job Object / cgroup mechanisms; on the POSIX process-group
    /// fallback an unreaped just-exited child may still be listed as a member —
    /// see [`ProcessGroup::members`](processkit::ProcessGroup::members)).
    /// `soft_terminate` describes the soft-stop tier for a runner-imposed ending
    /// (`signalled` | `unsupported` | `failed`), and is `null` on the natural-exit
    /// path where no soft stop is attempted.
    CleanupFinished {
        remaining: usize,
        remaining_pids: Vec<u32>,
        soft_terminate: Option<&'static str>,
    },
    /// A configured ProcessKit resource limit was exceeded or could not be
    /// applied. Part of the v1 schema so adapters pin its shape now; the runner
    /// exposes no resource-limit knobs yet, so it is not emitted at runtime today
    /// (see `docs/schema.md`, "limit_hit").
    // Reserved for when resource-limit configuration lands; constructed by the
    // golden test, so it is otherwise never built in this build.
    #[allow(dead_code)]
    LimitHit {
        /// Which limit was hit, e.g. `processes` / `memory` / `cpu`.
        limit: String,
        detail: Option<String>,
    },
    /// The `--timeout` deadline elapsed while the child was still running. The
    /// teardown it triggers is described by the following cleanup events.
    Timeout {
        timeout_ms: u64,
        grace_ms: Option<u64>,
    },
    /// The run was cancelled interactively (`Ctrl-C`). `source` is `ctrl_c`.
    Cancelled {
        source: &'static str,
        grace_ms: Option<u64>,
    },
    /// The program could not be started (not found / not executable / bad cwd):
    /// the child never ran. `code` is the runner-band exit code (`SPAWN`).
    SpawnFailed { code: u8, message: String },
    /// Creating the container or joining the child to it failed. `phase` is
    /// `create` (the group could not be created) or `attach` (the launch into the
    /// group failed for a non-spawn reason). `code` is the runner-band exit code
    /// (`BACKEND`).
    ContainerFailed {
        phase: &'static str,
        code: u8,
        message: String,
    },
    /// The terminal event of every run: the exact code the runner process returns.
    /// Always emitted — including on the runner's own failure — so a child's code
    /// is never lost or aliased (`AGENTS.md`, "Exit-code fidelity"). `source`
    /// names why the runner exited (`child_exit` | `timeout` | `cancelled` |
    /// `spawn_error` | `container_error` | `internal`); `child_code` carries the
    /// child's own code when it exited on its own, and is `null` for a
    /// runner-imposed ending or a child that never produced one.
    RunnerExit {
        code: i32,
        source: &'static str,
        child_code: Option<i32>,
    },
}

/// One entry of a [`Event::MembersSnapshot`]. Only `pid` is populated today; the
/// enriched fields are declared for the schema but filled `null` until ProcessKit
/// ships `members_info()` (module docs).
#[derive(Debug, Serialize)]
pub struct Member {
    pub pid: u32,
    pub ppid: Option<u32>,
    pub name: Option<String>,
    pub start_time: Option<String>,
}

impl Member {
    /// A member built from a bare PID: every enriched field is explicitly absent.
    pub fn from_pid(pid: u32) -> Self {
        Self {
            pid,
            ppid: None,
            name: None,
            start_time: None,
        }
    }
}

/// The command a run executed, in its redaction-aware v1 shape. `redacted` is
/// `true` by default and `false` only under `--argv-raw`; `argv` carries the raw
/// argv strings only when not redacted. `argv_sha256` (a one-way fingerprint) and
/// `hint` (a worker-shape category, or `null` when unrecognized) are filled on
/// every run — they never expose the command line — so redaction never blinds a
/// consumer to *which* run it is looking at (see [`argv_sha256_hex`],
/// [`classify_hint`], and `docs/schema.md`, "Command redaction").
#[derive(Debug, Serialize)]
pub struct CommandInfo {
    redacted: bool,
    argv: Option<Vec<String>>,
    argv_sha256: Option<String>,
    hint: Option<String>,
}

impl CommandInfo {
    /// Build the command field for `argv`. The one-way `argv_sha256` fingerprint
    /// and the worker-shape `hint` are always computed — neither can leak the
    /// command line — so they are present whether or not the raw argv is recorded.
    /// `argv_raw` additionally records the raw argv array verbatim; without it the
    /// argv is omitted (redacted) and only the fingerprint and hint remain.
    pub fn for_argv<I, S>(argv: I, argv_raw: bool) -> Self
    where
        I: IntoIterator<Item = S>,
        S: AsRef<std::ffi::OsStr>,
    {
        // Render argv once to the lossy-UTF-8 strings that `--argv-raw` would
        // record and the classifier inspects, then derive the fingerprint and hint
        // from that single rendering. Only the raw array is gated behind the flag;
        // the redaction-safe fields are computed unconditionally.
        let strings: Vec<String> = argv
            .into_iter()
            .map(|a| a.as_ref().to_string_lossy().into_owned())
            .collect();
        let argv_sha256 = Some(argv_sha256_hex(&strings));
        let hint = classify_hint(&strings).map(str::to_string);
        Self {
            redacted: !argv_raw,
            argv: argv_raw.then_some(strings),
            argv_sha256,
            hint,
        }
    }
}

/// The hex SHA-256 fingerprint of a run's argv: the lossy-UTF-8 argv elements
/// joined by a single NUL byte — a byte that cannot occur inside a real argv
/// element on any platform, so element boundaries stay unambiguous — then hashed.
/// This canonical encoding is documented in `docs/schema.md` ("Command redaction")
/// so an adapter that re-emits the schema reproduces the exact digest. The hash is
/// one-way, so it fingerprints a command without disclosing it.
fn argv_sha256_hex(argv: &[String]) -> String {
    sha256_hex(argv.join("\0").as_bytes())
}

/// One worker-shape classifier rule: the `hint` it emits and the set of substrings
/// that must **all** be present in a run's argv for it to match.
struct HintRule {
    /// The `hint` value emitted when every marker below is found in the argv.
    hint: &'static str,
    /// Substrings that must all appear (case-insensitively) in the argv. Stored in
    /// their readable, documented form; matching lowercases both sides.
    markers: &'static [&'static str],
}

/// The worker-shape hint catalog: plain, ordered data rather than branch logic, so
/// a new shape is one new entry here — and the same table is mirrored in
/// `docs/schema.md`, keeping the catalog visible outside the code. The first rule
/// whose markers all match wins; an argv matching none yields `null`.
///
/// Seed entry — **MSBuild reusable worker nodes.** A build host keeps long-lived
/// `MSBuild.dll` worker processes around (`/nodemode:1 /nodeReuse:true`); they are
/// a classic "stuck after the build" tree. Tagging the shape lets a consumer (the
/// orchestrator) name such a node without its full, possibly secret-bearing
/// command line.
static HINT_RULES: &[HintRule] = &[HintRule {
    hint: "msbuild_node_reuse",
    markers: &["MSBuild.dll", "/nodemode:1", "/nodeReuse:true"],
}];

/// Classify a run's argv against [`HINT_RULES`], returning the first matching
/// rule's `hint` or `None` when no shape is recognized (the common case). Matching
/// is a case-insensitive substring test over the space-joined argv, so a marker is
/// found whether it is a whole argument or embedded in one (e.g. a full
/// `…/MSBuild.dll` path). The hint is a fixed category label — never argv content —
/// so emitting it does not weaken redaction.
fn classify_hint(argv: &[String]) -> Option<&'static str> {
    let haystack = argv.join(" ").to_ascii_lowercase();
    HINT_RULES
        .iter()
        .find(|rule| {
            rule.markers
                .iter()
                .all(|marker| haystack.contains(marker.to_ascii_lowercase().as_str()))
        })
        .map(|rule| rule.hint)
}

/// SHA-256 (FIPS 180-4) of `bytes` as a lowercase hex string. Hand-rolled — like
/// [`format_rfc3339_utc`] — to keep the argv fingerprint dependency-free for a
/// single field; correctness is pinned against the FIPS example vectors in
/// [`tests::sha256_matches_known_vectors`]. This is a stable fingerprint, not an
/// adversarial-integrity primitive; the one property relied on here is that it does
/// not disclose its input.
fn sha256_hex(bytes: &[u8]) -> String {
    // Round constants: the first 32 bits of the fractional parts of the cube roots
    // of the first 64 primes (FIPS 180-4, §4.2.2).
    #[rustfmt::skip]
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
        0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
        0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
        0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
        0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
        0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
        0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
    ];
    // Initial hash values: the first 32 bits of the fractional parts of the square
    // roots of the first 8 primes (FIPS 180-4, §5.3.3).
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];

    // Pre-processing: append the `0x80` terminator, pad with zeros to 56 mod 64,
    // then the original message length in bits as a big-endian u64.
    let bit_len = (bytes.len() as u64).wrapping_mul(8);
    let mut msg = Vec::with_capacity(bytes.len() + 72);
    msg.extend_from_slice(bytes);
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&bit_len.to_be_bytes());

    let mut w = [0u32; 64];
    for block in msg.chunks_exact(64) {
        for (word, src) in w.iter_mut().zip(block.chunks_exact(4)) {
            *word = u32::from_be_bytes([src[0], src[1], src[2], src[3]]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }

        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
        for (&ki, &wi) in K.iter().zip(w.iter()) {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ ((!e) & g);
            let t1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(ki)
                .wrapping_add(wi);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        for (slot, value) in h.iter_mut().zip([a, b, c, d, e, f, g, hh]) {
            *slot = slot.wrapping_add(value);
        }
    }

    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(64);
    for word in h {
        for byte in word.to_be_bytes() {
            out.push(char::from(HEX[(byte >> 4) as usize]));
            out.push(char::from(HEX[(byte & 0x0f) as usize]));
        }
    }
    out
}

/// Append-only writer for a run's JSONL event stream.
///
/// Each event is written as one line and **flushed immediately**: the runner
/// forwards a completed child's code via [`std::process::exit`], which skips
/// destructors, so a buffered event (including the terminal `runner_exit`) would
/// be lost without a per-event flush. A write failure after the stream is open is
/// best-effort — it warns once on stderr and drops subsequent events rather than
/// aborting an otherwise-healthy run (the child's exit-code fidelity outranks
/// diagnostics); the fail-closed check is at [`Emitter::create`], before the child
/// is ever spawned.
pub struct Emitter {
    file: std::fs::File,
    poisoned: bool,
}

impl Emitter {
    /// Open (creating or truncating) the JSONL file for this run. Fails if the
    /// path cannot be created — the caller treats that as a runner-own failure and
    /// never spawns the child, so no child code can be lost to a logging setup
    /// error.
    pub fn create(path: &Path) -> std::io::Result<Self> {
        let file = std::fs::File::create(path)?;
        Ok(Self {
            file,
            poisoned: false,
        })
    }

    /// Emit one event, stamped with the current time. Infallible by contract: a
    /// write error is reported once to stderr and then swallowed (see the type
    /// docs), so lifecycle wiring never has to branch on logging failure.
    pub fn emit(&mut self, event: &Event) {
        if self.poisoned {
            return;
        }
        let line = match serialize_record(event, now_rfc3339()) {
            Ok(line) => line,
            Err(err) => {
                // A struct with string keys and no I/O cannot fail to serialize;
                // treat the impossible as best-effort rather than panicking.
                self.poison(format_args!("could not serialize a JSONL event: {err}"));
                return;
            }
        };
        if let Err(err) = self
            .file
            .write_all(line.as_bytes())
            .and_then(|()| self.file.write_all(b"\n"))
            .and_then(|()| self.file.flush())
        {
            self.poison(format_args!("could not write a JSONL event: {err}"));
        }
    }

    /// Warn once, then silence further events. Keeps a broken log from spamming
    /// stderr while still surfacing the first failure honestly.
    fn poison(&mut self, reason: std::fmt::Arguments<'_>) {
        eprintln!("processkit-cli: warning: JSONL event logging disabled: {reason}");
        self.poisoned = true;
    }
}

/// Serialize one enveloped event to a compact single-line JSON string (no trailing
/// newline). Separated from [`Emitter::emit`] so tests can render with a fixed
/// timestamp for the golden fixture.
fn serialize_record(event: &Event, time: String) -> serde_json::Result<String> {
    serde_json::to_string(&Record {
        schema_version: SCHEMA_VERSION,
        time,
        event,
    })
}

/// The run identifier for this run: the explicit `--run-id` when given, otherwise
/// a generated value unique per invocation on this host (`run-<pid>-<unix_nanos>`).
pub fn resolve_run_id(explicit: Option<&str>) -> String {
    match explicit {
        Some(id) => id.to_string(),
        None => {
            let nanos = SystemTime::now()
                .duration_since(SystemTime::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0);
            format!("run-{}-{nanos}", std::process::id())
        }
    }
}

/// The stable schema string for a containment [`Mechanism`]. `Mechanism` is
/// `#[non_exhaustive]`, so an unknown future variant maps to `"unknown"` rather
/// than a guess.
pub fn mechanism_str(mechanism: Mechanism) -> &'static str {
    match mechanism {
        Mechanism::JobObject => "job_object",
        Mechanism::CgroupV2 => "cgroup_v2",
        Mechanism::ProcessGroup => "process_group",
        _ => "unknown",
    }
}

/// Decompose a completed run's [`Outcome`] into the `root_exited` fields:
/// `(outcome, code, signal)`. `Outcome` is `#[non_exhaustive]`; an unrecognized
/// variant is reported as `"unknown"` with neither a code nor a signal.
pub fn outcome_fields(outcome: &Outcome) -> (&'static str, Option<i32>, Option<i32>) {
    match outcome {
        Outcome::Exited(code) => ("exited", Some(*code), None),
        Outcome::Signalled(Some(signal)) => ("signalled", None, Some(*signal)),
        Outcome::Signalled(None) => ("signalled", None, None),
        Outcome::TimedOut => ("timed_out", None, None),
        _ => ("unknown", None, None),
    }
}

/// The current time formatted for the event envelope.
fn now_rfc3339() -> String {
    format_rfc3339_utc(SystemTime::now())
}

/// Format a [`SystemTime`] as RFC 3339 UTC with millisecond precision
/// (`YYYY-MM-DDTHH:MM:SS.sssZ`). Hand-rolled to avoid a date-library dependency
/// for a single field; the civil-date conversion is Howard Hinnant's standard
/// `civil_from_days` algorithm (validated in [`tests::timestamp_matches_known_vectors`]).
///
/// `pub(crate)` so the run registry ([`crate::registry`]) stamps its record's
/// `started_at` with the same formatter rather than duplicating the civil-date math.
pub(crate) fn format_rfc3339_utc(time: SystemTime) -> String {
    let dur = time
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or(Duration::ZERO);
    let secs = dur.as_secs() as i64;
    let millis = dur.subsec_millis();

    let days = secs.div_euclid(86_400);
    let secs_of_day = secs.rem_euclid(86_400);
    let (hour, minute, second) = (
        secs_of_day / 3_600,
        (secs_of_day % 3_600) / 60,
        secs_of_day % 60,
    );
    let (year, month, day) = civil_from_days(days);
    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}.{millis:03}Z")
}

/// Convert a count of days since the Unix epoch (1970-01-01) into a
/// `(year, month, day)` civil date — Howard Hinnant's `civil_from_days`
/// (<http://howardhinnant.github.io/date_algorithms.html>), valid across the full
/// proleptic Gregorian range.
fn civil_from_days(days: i64) -> (i64, u32, u32) {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097; // [0, 146096]
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365; // [0, 399]
    let year = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153; // [0, 11]
    let day = (doy - (153 * mp + 2) / 5 + 1) as u32; // [1, 31]
    let month = if mp < 10 { mp + 3 } else { mp - 9 } as u32; // [1, 12]
    let year = year + i64::from(month <= 2);
    (year, month, day)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// A fixed timestamp for deterministic golden rendering, produced by the real
    /// formatter so the fixture also pins the timestamp shape.
    fn fixed_time() -> String {
        format_rfc3339_utc(SystemTime::UNIX_EPOCH + Duration::from_millis(1_700_000_000_123))
    }

    /// One representative instance of every event variant, in lifecycle order — the
    /// sample stream captured by the golden fixture. `run_started` appears twice on
    /// purpose: once redacted-by-default and once under `--argv-raw`, so the fixture
    /// pins **both** command-redaction branches — and shows that the `argv_sha256`
    /// fingerprint and the `hint` are identical either way (they never depend on
    /// whether the raw argv is disclosed).
    fn sample_events() -> Vec<Event> {
        // An MSBuild reusable-worker argv: a recognized worker shape, so the fixture
        // also demonstrates a populated `hint` next to the fingerprint.
        let msbuild_argv = [
            "C:\\Program Files\\dotnet\\sdk\\MSBuild.dll",
            "/nodemode:1",
            "/nodeReuse:true",
        ];
        vec![
            Event::RunStarted {
                run_id: "run-000".to_string(),
                root_pid: Some(4242),
                mechanism: mechanism_str(Mechanism::JobObject),
                cwd: Some("/work/project".to_string()),
                command: CommandInfo::for_argv(msbuild_argv, false),
            },
            Event::RunStarted {
                run_id: "run-001".to_string(),
                root_pid: Some(4242),
                mechanism: mechanism_str(Mechanism::JobObject),
                cwd: Some("/work/project".to_string()),
                command: CommandInfo::for_argv(msbuild_argv, true),
            },
            Event::MembersSnapshot {
                members: vec![Member::from_pid(4242), Member::from_pid(4243)],
            },
            Event::RootExited {
                outcome: "exited",
                code: Some(0),
                signal: None,
            },
            Event::CleanupStarted { members_before: 2 },
            Event::CleanupFinished {
                remaining: 0,
                remaining_pids: vec![],
                soft_terminate: None,
            },
            Event::LimitHit {
                limit: "processes".to_string(),
                detail: Some("exceeded the 64-process cap".to_string()),
            },
            Event::Timeout {
                timeout_ms: 5_000,
                grace_ms: Some(2_000),
            },
            Event::Cancelled {
                source: "ctrl_c",
                grace_ms: Some(2_000),
            },
            Event::SpawnFailed {
                code: 101,
                message: "could not start the program: program not found".to_string(),
            },
            Event::ContainerFailed {
                phase: "create",
                code: 102,
                message: "could not create the ProcessKit container".to_string(),
            },
            Event::RunnerExit {
                code: 0,
                source: "child_exit",
                child_code: Some(0),
            },
        ]
    }

    fn golden_path() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures/schema/v1/events.jsonl")
    }

    /// Render the sample stream exactly as the emitter would write it (one flushed
    /// line per event, trailing newline included).
    fn render_sample_stream() -> String {
        let time = fixed_time();
        let mut out = String::new();
        for event in sample_events() {
            out.push_str(&serialize_record(&event, time.clone()).expect("event serializes"));
            out.push('\n');
        }
        out
    }

    /// The golden gate (`AGENTS.md`, "Golden-schema tests"): the serialized sample
    /// stream must match the committed fixture byte-for-byte. Set
    /// `UPDATE_SCHEMA_GOLDEN=1` to rewrite the fixture after an intentional,
    /// version-bumped schema change.
    #[test]
    fn golden_stream_matches_the_fixture() {
        let rendered = render_sample_stream();
        if std::env::var_os("UPDATE_SCHEMA_GOLDEN").is_some() {
            std::fs::write(golden_path(), &rendered).expect("rewrite golden fixture");
        }
        let expected = std::fs::read_to_string(golden_path()).unwrap_or_else(|err| {
            panic!(
                "read golden fixture {}: {err}; regenerate with UPDATE_SCHEMA_GOLDEN=1",
                golden_path().display()
            )
        });
        assert_eq!(
            rendered, expected,
            "JSONL schema drift from fixtures/schema/v1/events.jsonl; if intended, bump \
             SCHEMA_VERSION and regenerate with UPDATE_SCHEMA_GOLDEN=1"
        );
    }

    /// The core envelope invariant: every event carries `schema_version` and a
    /// snake_case `event` type tag.
    #[test]
    fn every_event_carries_schema_version_and_a_type_tag() {
        for event in sample_events() {
            let line = serialize_record(&event, fixed_time()).expect("serializes");
            let value: serde_json::Value = serde_json::from_str(&line).expect("valid JSON");
            assert_eq!(
                value["schema_version"], 1,
                "every event must carry schema_version=1: {line}"
            );
            assert!(
                value.get("event").and_then(|v| v.as_str()).is_some(),
                "every event must carry a string `event` tag: {line}"
            );
        }
    }

    /// A member built from a bare PID declares the enriched fields but marks each
    /// explicitly absent (JSON `null`) — never omitted, never invented.
    #[test]
    fn members_enriched_fields_are_present_but_null_from_bare_pids() {
        let member = Member::from_pid(4242);
        assert_eq!(member.pid, 4242);
        assert!(member.ppid.is_none() && member.name.is_none() && member.start_time.is_none());

        let line = serialize_record(
            &Event::MembersSnapshot {
                members: vec![Member::from_pid(4242)],
            },
            fixed_time(),
        )
        .expect("serializes");
        let value: serde_json::Value = serde_json::from_str(&line).expect("valid JSON");
        let member = &value["members"][0];
        assert_eq!(member["pid"], 4242);
        for field in ["ppid", "name", "start_time"] {
            assert!(
                member.get(field).map(|v| v.is_null()).unwrap_or(false),
                "enriched field `{field}` must be present and null: {line}"
            );
        }
    }

    /// Whether `s` is a 64-character lowercase-hex string — the shape of an
    /// `argv_sha256` fingerprint.
    fn is_sha256_hex(s: Option<&str>) -> bool {
        matches!(s, Some(s) if s.len() == 64 && s.bytes().all(|b| matches!(b, b'0'..=b'9' | b'a'..=b'f')))
    }

    /// Redacted-by-default vs `--argv-raw`, and the redaction-safe fields filled
    /// either way. A bare run omits the raw argv but still carries the fingerprint
    /// (and a `hint` when the shape is recognized); `--argv-raw` adds the raw argv
    /// without changing the fingerprint or the hint.
    #[test]
    fn command_info_redacts_by_default_and_honors_argv_raw() {
        // A non-worker argv: redacted, fingerprinted, no recognized hint.
        let redacted = CommandInfo::for_argv(["cmd", "/c", "secret"], false);
        assert!(redacted.redacted && redacted.argv.is_none());
        assert!(
            is_sha256_hex(redacted.argv_sha256.as_deref()),
            "a redacted command still carries a hex fingerprint: {:?}",
            redacted.argv_sha256
        );
        assert!(
            redacted.hint.is_none(),
            "an unrecognized shape has no hint: {:?}",
            redacted.hint
        );

        // `--argv-raw` records the raw argv while keeping the same fingerprint/hint.
        let raw = CommandInfo::for_argv(["cmd", "/c", "secret"], true);
        assert!(!raw.redacted);
        assert_eq!(
            raw.argv.as_deref(),
            Some(["cmd", "/c", "secret"].map(String::from).as_slice())
        );
        assert_eq!(
            raw.argv_sha256, redacted.argv_sha256,
            "the fingerprint does not depend on whether the raw argv is disclosed"
        );
        assert_eq!(raw.hint, redacted.hint);
    }

    /// The hand-rolled SHA-256 against the FIPS 180-4 example vectors — the gate
    /// that lets the fixture (and the fingerprint) be trusted.
    #[test]
    fn sha256_matches_known_vectors() {
        assert_eq!(
            sha256_hex(b""),
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
        );
        assert_eq!(
            sha256_hex(b"abc"),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        assert_eq!(
            sha256_hex(b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
            "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"
        );
    }

    /// The argv fingerprint is SHA-256 over the NUL-joined argv: a single-element
    /// argv hashes exactly its one element (no separator), and the NUL boundary
    /// keeps element splits significant so distinct argvs cannot collide.
    #[test]
    fn argv_fingerprint_is_canonical_and_boundary_sensitive() {
        // One element: the join adds no separator, so it equals SHA-256("abc").
        assert_eq!(
            argv_sha256_hex(&["abc".to_string()]),
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
        );
        // The NUL separator makes element boundaries significant: ["a","b"] and
        // ["ab"] are different argvs and must not fingerprint alike.
        assert_ne!(
            argv_sha256_hex(&["a".to_string(), "b".to_string()]),
            argv_sha256_hex(&["ab".to_string()])
        );
    }

    /// The hint classifier tags an MSBuild reusable-worker argv (case-insensitively,
    /// wherever the markers sit) and leaves everything else unclassified.
    #[test]
    fn classify_hint_recognizes_msbuild_and_ignores_unknown() {
        let msbuild = [
            "C:\\dotnet\\MSBuild.dll".to_string(),
            "/nodemode:1".to_string(),
            "/nodeReuse:true".to_string(),
        ];
        assert_eq!(classify_hint(&msbuild), Some("msbuild_node_reuse"));

        // Case-insensitive: a lowercased argv still matches.
        let lowercased = [
            "msbuild.dll".to_string(),
            "/nodemode:1".to_string(),
            "/nodereuse:true".to_string(),
        ];
        assert_eq!(classify_hint(&lowercased), Some("msbuild_node_reuse"));

        // Missing one marker → no match.
        let partial = ["MSBuild.dll".to_string(), "/nodemode:1".to_string()];
        assert_eq!(classify_hint(&partial), None);

        // An ordinary command is unclassified.
        assert_eq!(
            classify_hint(&["cmd".to_string(), "/c".to_string(), "build".to_string()]),
            None
        );
    }

    #[test]
    fn mechanism_maps_to_the_documented_strings() {
        assert_eq!(mechanism_str(Mechanism::JobObject), "job_object");
        assert_eq!(mechanism_str(Mechanism::CgroupV2), "cgroup_v2");
        assert_eq!(mechanism_str(Mechanism::ProcessGroup), "process_group");
    }

    #[test]
    fn outcome_fields_split_code_from_signal() {
        assert_eq!(
            outcome_fields(&Outcome::Exited(7)),
            ("exited", Some(7), None)
        );
        assert_eq!(
            outcome_fields(&Outcome::Signalled(Some(9))),
            ("signalled", None, Some(9))
        );
        assert_eq!(
            outcome_fields(&Outcome::Signalled(None)),
            ("signalled", None, None)
        );
        assert_eq!(
            outcome_fields(&Outcome::TimedOut),
            ("timed_out", None, None)
        );
    }

    /// `runner_exit` keeps the child's own code in `child_code` even though `code`
    /// is what the process returns — the "child code is never lost" contract in
    /// its machine form.
    #[test]
    fn runner_exit_preserves_the_child_code_separately() {
        let child = Event::RunnerExit {
            code: 7,
            source: "child_exit",
            child_code: Some(7),
        };
        let value: serde_json::Value =
            serde_json::from_str(&serialize_record(&child, fixed_time()).unwrap()).unwrap();
        assert_eq!(value["code"], 7);
        assert_eq!(value["child_code"], 7);
        assert_eq!(value["source"], "child_exit");

        // A runner-imposed ending forwards a runner-band code and no child code.
        let timeout = Event::RunnerExit {
            code: 106,
            source: "timeout",
            child_code: None,
        };
        let value: serde_json::Value =
            serde_json::from_str(&serialize_record(&timeout, fixed_time()).unwrap()).unwrap();
        assert_eq!(value["code"], 106);
        assert!(value["child_code"].is_null());
    }

    /// The hand-rolled UTC formatter against well-known epoch instants.
    #[test]
    fn timestamp_matches_known_vectors() {
        let at = |secs: u64| format_rfc3339_utc(SystemTime::UNIX_EPOCH + Duration::from_secs(secs));
        assert_eq!(at(0), "1970-01-01T00:00:00.000Z");
        assert_eq!(at(86_400), "1970-01-02T00:00:00.000Z");
        // The classic Unix "billennium".
        assert_eq!(at(1_000_000_000), "2001-09-09T01:46:40.000Z");
        assert_eq!(at(1_609_459_200), "2021-01-01T00:00:00.000Z");
        // Millisecond precision is preserved.
        assert_eq!(
            format_rfc3339_utc(SystemTime::UNIX_EPOCH + Duration::from_millis(1_609_459_200_123)),
            "2021-01-01T00:00:00.123Z"
        );
    }
}
