//! The versioned JSONL lifecycle-event schema and its emitter.
//!
//! This module owns processkit-cli's **normative event contract** (`AGENTS.md`,
//! "This repository owns the normative JSONL schema"): every event is one JSON
//! object on its own line, carrying a `schema_version`, written only to the
//! `--jsonl` file — never to stdout, so the child's stream stays pristine
//! (`AGENTS.md`, "Streams are strictly separated"). Adapters (processkit-py's
//! CLI) pin `schema_version` and reimplement these shapes, so the field set here
//! is a public API: `docs/schema.md` is the human-readable normative document and
//! `fixtures/schema/v1/events.jsonl` is the golden material adapters test against
//! (regenerated by [`tests::golden_stream_matches_the_fixture`]).
//!
//! Two shapes are deliberately *forward-declared* now so their appearance later
//! does not change an event's wire form:
//!
//! - **Enriched member fields.** ProcessKit's public API returns bare PIDs today;
//!   the richer per-member snapshot (`ppid` / executable `name` / `start_time`)
//!   is a filed-but-unshipped ProcessKit-rs capability
//!   (`ProcessGroup::members_info()`). So [`Member`] declares those fields as
//!   optional and the emitter fills them from bare PIDs alone, marking every
//!   richer field explicitly **absent** (JSON `null`) rather than inventing a
//!   local process-enumeration path (`AGENTS.md`, "Build strictly on the public
//!   `processkit` API").
//! - **Command line / argv.** Command lines carry secrets, so argv is redacted by
//!   default (`AGENTS.md`, "Argv is redacted by default"). The redaction
//!   *machinery* — the SHA-256 of argv plus the worker-shape hint classifier —
//!   lands in T-005; [`CommandInfo`] already reserves `argv_sha256` and `hint`
//!   (null until then) and honors `--argv-raw` for the raw array now, so T-005
//!   only fills existing fields and never reshapes the event.

use std::io::Write;
use std::path::Path;
use std::time::{Duration, SystemTime};

use serde::Serialize;

use processkit::{Mechanism, Outcome};

/// The schema version stamped on every event. Part of the compatibility surface:
/// any breaking change to an event's shape is a **major** bump of this number
/// (`docs/schema.md`, "Versioning").
pub const SCHEMA_VERSION: u32 = 1;

/// The wire record actually serialized per line: the common envelope
/// (`schema_version`, `time`) plus the flattened event body (its `event` type tag
/// and payload). Field order here is the on-the-wire order and is stable.
#[derive(Serialize)]
struct Record<'a> {
    schema_version: u32,
    /// Emission time, RFC 3339 UTC with millisecond precision. For `root_exited`
    /// this doubles as the required exit timestamp — the moment the runner
    /// observed the child leave.
    time: String,
    #[serde(flatten)]
    event: &'a Event,
}

/// One lifecycle event. Internally tagged (`"event": "<snake_case>"`) so each line
/// is self-describing; every variant is documented in `docs/schema.md`.
#[derive(Debug, Serialize)]
#[serde(tag = "event", rename_all = "snake_case")]
pub enum Event {
    /// The run has started: the child is spawned into the container and its root
    /// PID, the containment mechanism, the working directory, and the (redacted)
    /// command are known.
    RunStarted {
        run_id: String,
        /// The root child's PID. `null` if the backend did not expose one.
        root_pid: Option<u32>,
        /// `job_object` | `cgroup_v2` | `process_group` (see [`mechanism_str`]).
        mechanism: &'static str,
        /// Working directory the child runs in, or `null` if it could not be
        /// resolved.
        cwd: Option<String>,
        command: CommandInfo,
    },
    /// A point-in-time snapshot of the container's members. PID-only today; the
    /// richer fields are declared but absent (see module docs and [`Member`]).
    MembersSnapshot { members: Vec<Member> },
    /// The root child exited on its own. `code` is set for a normal exit; `signal`
    /// for a Unix signal death; both `null` only for an outcome without either.
    RootExited {
        /// `exited` | `signalled` | `timed_out` | `unknown` (see [`outcome_fields`]).
        outcome: &'static str,
        code: Option<i32>,
        signal: Option<i32>,
    },
    /// Container teardown is beginning; `members_before` is the tree size about to
    /// be reaped.
    CleanupStarted { members_before: usize },
    /// Container teardown finished. `remaining_pids` is a post-hard-kill snapshot
    /// (empty on the Job Object / cgroup mechanisms; on the POSIX process-group
    /// fallback an unreaped just-exited child may still be listed as a member —
    /// see [`ProcessGroup::members`](processkit::ProcessGroup::members)).
    /// `soft_terminate` describes the soft-stop tier for a runner-imposed ending
    /// (`signalled` | `unsupported` | `failed`), and is `null` on the natural-exit
    /// path where no soft stop is attempted.
    CleanupFinished {
        remaining: usize,
        remaining_pids: Vec<u32>,
        soft_terminate: Option<&'static str>,
    },
    /// A configured ProcessKit resource limit was exceeded or could not be
    /// applied. Part of the v1 schema so adapters pin its shape now; the runner
    /// exposes no resource-limit knobs yet, so it is not emitted at runtime today
    /// (see `docs/schema.md`, "limit_hit").
    // Reserved for when resource-limit configuration lands; constructed by the
    // golden test, so it is otherwise never built in this build.
    #[allow(dead_code)]
    LimitHit {
        /// Which limit was hit, e.g. `processes` / `memory` / `cpu`.
        limit: String,
        detail: Option<String>,
    },
    /// The `--timeout` deadline elapsed while the child was still running. The
    /// teardown it triggers is described by the following cleanup events.
    Timeout {
        timeout_ms: u64,
        grace_ms: Option<u64>,
    },
    /// The run was cancelled interactively (`Ctrl-C`). `source` is `ctrl_c`.
    Cancelled {
        source: &'static str,
        grace_ms: Option<u64>,
    },
    /// The program could not be started (not found / not executable / bad cwd):
    /// the child never ran. `code` is the runner-band exit code (`SPAWN`).
    SpawnFailed { code: u8, message: String },
    /// Creating the container or joining the child to it failed. `phase` is
    /// `create` (the group could not be created) or `attach` (the launch into the
    /// group failed for a non-spawn reason). `code` is the runner-band exit code
    /// (`BACKEND`).
    ContainerFailed {
        phase: &'static str,
        code: u8,
        message: String,
    },
    /// The terminal event of every run: the exact code the runner process returns.
    /// Always emitted — including on the runner's own failure — so a child's code
    /// is never lost or aliased (`AGENTS.md`, "Exit-code fidelity"). `source`
    /// names why the runner exited (`child_exit` | `timeout` | `cancelled` |
    /// `spawn_error` | `container_error` | `internal`); `child_code` carries the
    /// child's own code when it exited on its own, and is `null` for a
    /// runner-imposed ending or a child that never produced one.
    RunnerExit {
        code: i32,
        source: &'static str,
        child_code: Option<i32>,
    },
}

/// One entry of a [`Event::MembersSnapshot`]. Only `pid` is populated today; the
/// enriched fields are declared for the schema but filled `null` until ProcessKit
/// ships `members_info()` (module docs).
#[derive(Debug, Serialize)]
pub struct Member {
    pub pid: u32,
    pub ppid: Option<u32>,
    pub name: Option<String>,
    pub start_time: Option<String>,
}

impl Member {
    /// A member built from a bare PID: every enriched field is explicitly absent.
    pub fn from_pid(pid: u32) -> Self {
        Self {
            pid,
            ppid: None,
            name: None,
            start_time: None,
        }
    }
}

/// The command a run executed, in its redaction-aware v1 shape. `redacted` is
/// `true` by default and `false` only under `--argv-raw`; `argv` carries the raw
/// argv strings only when not redacted. `argv_sha256` and `hint` are reserved for
/// the T-005 redaction machinery and are `null` in v1 (see module docs).
#[derive(Debug, Serialize)]
pub struct CommandInfo {
    redacted: bool,
    argv: Option<Vec<String>>,
    argv_sha256: Option<String>,
    hint: Option<String>,
}

impl CommandInfo {
    /// Build the command field for `argv`. With `argv_raw` set the raw argv is
    /// recorded verbatim; otherwise it is redacted (argv omitted) and the hash +
    /// hint stay null until T-005 fills them.
    pub fn for_argv<I, S>(argv: I, argv_raw: bool) -> Self
    where
        I: IntoIterator<Item = S>,
        S: AsRef<std::ffi::OsStr>,
    {
        let argv = if argv_raw {
            Some(
                argv.into_iter()
                    .map(|a| a.as_ref().to_string_lossy().into_owned())
                    .collect(),
            )
        } else {
            None
        };
        Self {
            redacted: !argv_raw,
            argv,
            argv_sha256: None,
            hint: None,
        }
    }
}

/// Append-only writer for a run's JSONL event stream.
///
/// Each event is written as one line and **flushed immediately**: the runner
/// forwards a completed child's code via [`std::process::exit`], which skips
/// destructors, so a buffered event (including the terminal `runner_exit`) would
/// be lost without a per-event flush. A write failure after the stream is open is
/// best-effort — it warns once on stderr and drops subsequent events rather than
/// aborting an otherwise-healthy run (the child's exit-code fidelity outranks
/// diagnostics); the fail-closed check is at [`Emitter::create`], before the child
/// is ever spawned.
pub struct Emitter {
    file: std::fs::File,
    poisoned: bool,
}

impl Emitter {
    /// Open (creating or truncating) the JSONL file for this run. Fails if the
    /// path cannot be created — the caller treats that as a runner-own failure and
    /// never spawns the child, so no child code can be lost to a logging setup
    /// error.
    pub fn create(path: &Path) -> std::io::Result<Self> {
        let file = std::fs::File::create(path)?;
        Ok(Self {
            file,
            poisoned: false,
        })
    }

    /// Emit one event, stamped with the current time. Infallible by contract: a
    /// write error is reported once to stderr and then swallowed (see the type
    /// docs), so lifecycle wiring never has to branch on logging failure.
    pub fn emit(&mut self, event: &Event) {
        if self.poisoned {
            return;
        }
        let line = match serialize_record(event, now_rfc3339()) {
            Ok(line) => line,
            Err(err) => {
                // A struct with string keys and no I/O cannot fail to serialize;
                // treat the impossible as best-effort rather than panicking.
                self.poison(format_args!("could not serialize a JSONL event: {err}"));
                return;
            }
        };
        if let Err(err) = self
            .file
            .write_all(line.as_bytes())
            .and_then(|()| self.file.write_all(b"\n"))
            .and_then(|()| self.file.flush())
        {
            self.poison(format_args!("could not write a JSONL event: {err}"));
        }
    }

    /// Warn once, then silence further events. Keeps a broken log from spamming
    /// stderr while still surfacing the first failure honestly.
    fn poison(&mut self, reason: std::fmt::Arguments<'_>) {
        eprintln!("processkit-cli: warning: JSONL event logging disabled: {reason}");
        self.poisoned = true;
    }
}

/// Serialize one enveloped event to a compact single-line JSON string (no trailing
/// newline). Separated from [`Emitter::emit`] so tests can render with a fixed
/// timestamp for the golden fixture.
fn serialize_record(event: &Event, time: String) -> serde_json::Result<String> {
    serde_json::to_string(&Record {
        schema_version: SCHEMA_VERSION,
        time,
        event,
    })
}

/// The run identifier for this run: the explicit `--run-id` when given, otherwise
/// a generated value unique per invocation on this host (`run-<pid>-<unix_nanos>`).
pub fn resolve_run_id(explicit: Option<&str>) -> String {
    match explicit {
        Some(id) => id.to_string(),
        None => {
            let nanos = SystemTime::now()
                .duration_since(SystemTime::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0);
            format!("run-{}-{nanos}", std::process::id())
        }
    }
}

/// The stable schema string for a containment [`Mechanism`]. `Mechanism` is
/// `#[non_exhaustive]`, so an unknown future variant maps to `"unknown"` rather
/// than a guess.
pub fn mechanism_str(mechanism: Mechanism) -> &'static str {
    match mechanism {
        Mechanism::JobObject => "job_object",
        Mechanism::CgroupV2 => "cgroup_v2",
        Mechanism::ProcessGroup => "process_group",
        _ => "unknown",
    }
}

/// Decompose a completed run's [`Outcome`] into the `root_exited` fields:
/// `(outcome, code, signal)`. `Outcome` is `#[non_exhaustive]`; an unrecognized
/// variant is reported as `"unknown"` with neither a code nor a signal.
pub fn outcome_fields(outcome: &Outcome) -> (&'static str, Option<i32>, Option<i32>) {
    match outcome {
        Outcome::Exited(code) => ("exited", Some(*code), None),
        Outcome::Signalled(Some(signal)) => ("signalled", None, Some(*signal)),
        Outcome::Signalled(None) => ("signalled", None, None),
        Outcome::TimedOut => ("timed_out", None, None),
        _ => ("unknown", None, None),
    }
}

/// The current time formatted for the event envelope.
fn now_rfc3339() -> String {
    format_rfc3339_utc(SystemTime::now())
}

/// Format a [`SystemTime`] as RFC 3339 UTC with millisecond precision
/// (`YYYY-MM-DDTHH:MM:SS.sssZ`). Hand-rolled to avoid a date-library dependency
/// for a single field; the civil-date conversion is Howard Hinnant's standard
/// `civil_from_days` algorithm (validated in [`tests::timestamp_matches_known_vectors`]).
fn format_rfc3339_utc(time: SystemTime) -> String {
    let dur = time
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or(Duration::ZERO);
    let secs = dur.as_secs() as i64;
    let millis = dur.subsec_millis();

    let days = secs.div_euclid(86_400);
    let secs_of_day = secs.rem_euclid(86_400);
    let (hour, minute, second) = (
        secs_of_day / 3_600,
        (secs_of_day % 3_600) / 60,
        secs_of_day % 60,
    );
    let (year, month, day) = civil_from_days(days);
    format!("{year:04}-{month:02}-{day:02}T{hour:02}:{minute:02}:{second:02}.{millis:03}Z")
}

/// Convert a count of days since the Unix epoch (1970-01-01) into a
/// `(year, month, day)` civil date — Howard Hinnant's `civil_from_days`
/// (<http://howardhinnant.github.io/date_algorithms.html>), valid across the full
/// proleptic Gregorian range.
fn civil_from_days(days: i64) -> (i64, u32, u32) {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = z - era * 146_097; // [0, 146096]
    let yoe = (doe - doe / 1_460 + doe / 36_524 - doe / 146_096) / 365; // [0, 399]
    let year = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100); // [0, 365]
    let mp = (5 * doy + 2) / 153; // [0, 11]
    let day = (doy - (153 * mp + 2) / 5 + 1) as u32; // [1, 31]
    let month = if mp < 10 { mp + 3 } else { mp - 9 } as u32; // [1, 12]
    let year = year + i64::from(month <= 2);
    (year, month, day)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// A fixed timestamp for deterministic golden rendering, produced by the real
    /// formatter so the fixture also pins the timestamp shape.
    fn fixed_time() -> String {
        format_rfc3339_utc(SystemTime::UNIX_EPOCH + Duration::from_millis(1_700_000_000_123))
    }

    /// One representative instance of every event variant, in lifecycle order —
    /// the sample stream captured by the golden fixture.
    fn sample_events() -> Vec<Event> {
        vec![
            Event::RunStarted {
                run_id: "run-000".to_string(),
                root_pid: Some(4242),
                mechanism: mechanism_str(Mechanism::JobObject),
                cwd: Some("/work/project".to_string()),
                command: CommandInfo::for_argv(["cmd", "/c", "build"], false),
            },
            Event::MembersSnapshot {
                members: vec![Member::from_pid(4242), Member::from_pid(4243)],
            },
            Event::RootExited {
                outcome: "exited",
                code: Some(0),
                signal: None,
            },
            Event::CleanupStarted { members_before: 2 },
            Event::CleanupFinished {
                remaining: 0,
                remaining_pids: vec![],
                soft_terminate: None,
            },
            Event::LimitHit {
                limit: "processes".to_string(),
                detail: Some("exceeded the 64-process cap".to_string()),
            },
            Event::Timeout {
                timeout_ms: 5_000,
                grace_ms: Some(2_000),
            },
            Event::Cancelled {
                source: "ctrl_c",
                grace_ms: Some(2_000),
            },
            Event::SpawnFailed {
                code: 101,
                message: "could not start the program: program not found".to_string(),
            },
            Event::ContainerFailed {
                phase: "create",
                code: 102,
                message: "could not create the ProcessKit container".to_string(),
            },
            Event::RunnerExit {
                code: 0,
                source: "child_exit",
                child_code: Some(0),
            },
        ]
    }

    fn golden_path() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures/schema/v1/events.jsonl")
    }

    /// Render the sample stream exactly as the emitter would write it (one flushed
    /// line per event, trailing newline included).
    fn render_sample_stream() -> String {
        let time = fixed_time();
        let mut out = String::new();
        for event in sample_events() {
            out.push_str(&serialize_record(&event, time.clone()).expect("event serializes"));
            out.push('\n');
        }
        out
    }

    /// The golden gate (`AGENTS.md`, "Golden-schema tests"): the serialized sample
    /// stream must match the committed fixture byte-for-byte. Set
    /// `UPDATE_SCHEMA_GOLDEN=1` to rewrite the fixture after an intentional,
    /// version-bumped schema change.
    #[test]
    fn golden_stream_matches_the_fixture() {
        let rendered = render_sample_stream();
        if std::env::var_os("UPDATE_SCHEMA_GOLDEN").is_some() {
            std::fs::write(golden_path(), &rendered).expect("rewrite golden fixture");
        }
        let expected = std::fs::read_to_string(golden_path()).unwrap_or_else(|err| {
            panic!(
                "read golden fixture {}: {err}; regenerate with UPDATE_SCHEMA_GOLDEN=1",
                golden_path().display()
            )
        });
        assert_eq!(
            rendered, expected,
            "JSONL schema drift from fixtures/schema/v1/events.jsonl; if intended, bump \
             SCHEMA_VERSION and regenerate with UPDATE_SCHEMA_GOLDEN=1"
        );
    }

    /// The core envelope invariant: every event carries `schema_version` and a
    /// snake_case `event` type tag.
    #[test]
    fn every_event_carries_schema_version_and_a_type_tag() {
        for event in sample_events() {
            let line = serialize_record(&event, fixed_time()).expect("serializes");
            let value: serde_json::Value = serde_json::from_str(&line).expect("valid JSON");
            assert_eq!(
                value["schema_version"], 1,
                "every event must carry schema_version=1: {line}"
            );
            assert!(
                value.get("event").and_then(|v| v.as_str()).is_some(),
                "every event must carry a string `event` tag: {line}"
            );
        }
    }

    /// A member built from a bare PID declares the enriched fields but marks each
    /// explicitly absent (JSON `null`) — never omitted, never invented.
    #[test]
    fn members_enriched_fields_are_present_but_null_from_bare_pids() {
        let member = Member::from_pid(4242);
        assert_eq!(member.pid, 4242);
        assert!(member.ppid.is_none() && member.name.is_none() && member.start_time.is_none());

        let line = serialize_record(
            &Event::MembersSnapshot {
                members: vec![Member::from_pid(4242)],
            },
            fixed_time(),
        )
        .expect("serializes");
        let value: serde_json::Value = serde_json::from_str(&line).expect("valid JSON");
        let member = &value["members"][0];
        assert_eq!(member["pid"], 4242);
        for field in ["ppid", "name", "start_time"] {
            assert!(
                member.get(field).map(|v| v.is_null()).unwrap_or(false),
                "enriched field `{field}` must be present and null: {line}"
            );
        }
    }

    /// Redacted-by-default: a bare run omits argv and leaves the T-005 fields null;
    /// `--argv-raw` records the raw argv while the hash/hint stay reserved.
    #[test]
    fn command_info_redacts_by_default_and_honors_argv_raw() {
        let redacted = CommandInfo::for_argv(["cmd", "/c", "secret"], false);
        assert!(redacted.redacted && redacted.argv.is_none());
        assert!(redacted.argv_sha256.is_none() && redacted.hint.is_none());

        let raw = CommandInfo::for_argv(["cmd", "/c", "secret"], true);
        assert!(!raw.redacted);
        assert_eq!(
            raw.argv.as_deref(),
            Some(["cmd", "/c", "secret"].map(String::from).as_slice())
        );
        assert!(
            raw.argv_sha256.is_none() && raw.hint.is_none(),
            "the redaction machinery (hash/hint) is reserved for T-005"
        );
    }

    #[test]
    fn mechanism_maps_to_the_documented_strings() {
        assert_eq!(mechanism_str(Mechanism::JobObject), "job_object");
        assert_eq!(mechanism_str(Mechanism::CgroupV2), "cgroup_v2");
        assert_eq!(mechanism_str(Mechanism::ProcessGroup), "process_group");
    }

    #[test]
    fn outcome_fields_split_code_from_signal() {
        assert_eq!(
            outcome_fields(&Outcome::Exited(7)),
            ("exited", Some(7), None)
        );
        assert_eq!(
            outcome_fields(&Outcome::Signalled(Some(9))),
            ("signalled", None, Some(9))
        );
        assert_eq!(
            outcome_fields(&Outcome::Signalled(None)),
            ("signalled", None, None)
        );
        assert_eq!(
            outcome_fields(&Outcome::TimedOut),
            ("timed_out", None, None)
        );
    }

    /// `runner_exit` keeps the child's own code in `child_code` even though `code`
    /// is what the process returns — the "child code is never lost" contract in
    /// its machine form.
    #[test]
    fn runner_exit_preserves_the_child_code_separately() {
        let child = Event::RunnerExit {
            code: 7,
            source: "child_exit",
            child_code: Some(7),
        };
        let value: serde_json::Value =
            serde_json::from_str(&serialize_record(&child, fixed_time()).unwrap()).unwrap();
        assert_eq!(value["code"], 7);
        assert_eq!(value["child_code"], 7);
        assert_eq!(value["source"], "child_exit");

        // A runner-imposed ending forwards a runner-band code and no child code.
        let timeout = Event::RunnerExit {
            code: 106,
            source: "timeout",
            child_code: None,
        };
        let value: serde_json::Value =
            serde_json::from_str(&serialize_record(&timeout, fixed_time()).unwrap()).unwrap();
        assert_eq!(value["code"], 106);
        assert!(value["child_code"].is_null());
    }

    /// The hand-rolled UTC formatter against well-known epoch instants.
    #[test]
    fn timestamp_matches_known_vectors() {
        let at = |secs: u64| format_rfc3339_utc(SystemTime::UNIX_EPOCH + Duration::from_secs(secs));
        assert_eq!(at(0), "1970-01-01T00:00:00.000Z");
        assert_eq!(at(86_400), "1970-01-02T00:00:00.000Z");
        // The classic Unix "billennium".
        assert_eq!(at(1_000_000_000), "2001-09-09T01:46:40.000Z");
        assert_eq!(at(1_609_459_200), "2021-01-01T00:00:00.000Z");
        // Millisecond precision is preserved.
        assert_eq!(
            format_rfc3339_utc(SystemTime::UNIX_EPOCH + Duration::from_millis(1_609_459_200_123)),
            "2021-01-01T00:00:00.123Z"
        );
    }
}
